# Generated by Django 4.0.6 on 2022-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_slug_style_slug_term_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='slug',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
